[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"



[project]
name = "BlimpGymEnvironment"
version = "0.0.2"
dependencies = [
    "mujoco",
    "opencv-python",
    "setuptools",
    "numpy==1.26.4"
]
